/*
 * generated by Xtext 2.25.0
 */
package com.mike.berezhkov.huawei.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.mike.berezhkov.huawei.CPoCPRuntimeModule;
import com.mike.berezhkov.huawei.CPoCPStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CPoCPIdeSetup extends CPoCPStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CPoCPRuntimeModule(), new CPoCPIdeModule()));
	}
	
}
